//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:17 AM CET 
//


package com.ibm.ia.xmlns._default.rsa_demobank_bom.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClientReaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClientReaction">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model}Reaction">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlRootElement(name = "ClientReaction")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClientReaction")
public class ClientReaction
    extends Reaction
{


}
