//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:17 AM CET 
//


package com.ibm.ia.xmlns._default.rsa_demobank_bom.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MonitoringEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MonitoringEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientAge" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="clientLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clientSegment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="impulseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="impulseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promotionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="promotionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model}MonitoringEventType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoringEvent", propOrder = {
    "clientAge",
    "clientLanguage",
    "clientSegment",
    "datetime",
    "impulseId",
    "impulseName",
    "promotionId",
    "promotionName",
    "reaction",
    "type"
})
public class MonitoringEvent {

    protected double clientAge;
    @XmlElement(required = true)
    protected String clientLanguage;
    @XmlElement(required = true)
    protected String clientSegment;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetime;
    @XmlElement(required = true)
    protected String impulseId;
    @XmlElement(required = true)
    protected String impulseName;
    @XmlElement(required = true)
    protected String promotionId;
    @XmlElement(required = true)
    protected String promotionName;
    @XmlElement(required = true)
    protected String reaction;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MonitoringEventType type;

    /**
     * Gets the value of the clientAge property.
     * 
     */
    public double getClientAge() {
        return clientAge;
    }

    /**
     * Sets the value of the clientAge property.
     * 
     */
    public void setClientAge(double value) {
        this.clientAge = value;
    }

    /**
     * Gets the value of the clientLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientLanguage() {
        return clientLanguage;
    }

    /**
     * Sets the value of the clientLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientLanguage(String value) {
        this.clientLanguage = value;
    }

    /**
     * Gets the value of the clientSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientSegment() {
        return clientSegment;
    }

    /**
     * Sets the value of the clientSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSegment(String value) {
        this.clientSegment = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetime(XMLGregorianCalendar value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the impulseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpulseId() {
        return impulseId;
    }

    /**
     * Sets the value of the impulseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpulseId(String value) {
        this.impulseId = value;
    }

    /**
     * Gets the value of the impulseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpulseName() {
        return impulseName;
    }

    /**
     * Sets the value of the impulseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpulseName(String value) {
        this.impulseName = value;
    }

    /**
     * Gets the value of the promotionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionId() {
        return promotionId;
    }

    /**
     * Sets the value of the promotionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionId(String value) {
        this.promotionId = value;
    }

    /**
     * Gets the value of the promotionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * Sets the value of the promotionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionName(String value) {
        this.promotionName = value;
    }

    /**
     * Gets the value of the reaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaction() {
        return reaction;
    }

    /**
     * Sets the value of the reaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaction(String value) {
        this.reaction = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringEventType }
     *     
     */
    public MonitoringEventType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringEventType }
     *     
     */
    public void setType(MonitoringEventType value) {
        this.type = value;
    }

}
