//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:17 AM CET 
//


package com.ibm.ia.xmlns._default.rsa_demobank_bom.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitoringEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MonitoringEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PROMOTION_START"/>
 *     &lt;enumeration value="PROMOTION_END"/>
 *     &lt;enumeration value="IMPULSE"/>
 *     &lt;enumeration value="REACTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MonitoringEventType")
@XmlEnum
public enum MonitoringEventType {

    PROMOTION_START,
    PROMOTION_END,
    IMPULSE,
    REACTION;

    public String value() {
        return name();
    }

    public static MonitoringEventType fromValue(String v) {
        return valueOf(v);
    }

}
