//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.02 at 11:16:17 AM CET 
//


package com.ibm.ia.xmlns._default.rsa_demobank_bom.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.ia.xmlns._default.rsa_demobank_bom.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClientSetupEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "ClientSetupEvent");
    private final static QName _CRMReaction_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "CRMReaction");
    private final static QName _Impulse_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "Impulse");
    private final static QName _LetterImpulse_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "LetterImpulse");
    private final static QName _CRMImpulse_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "CRMImpulse");
    private final static QName _ClientActivityEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "ClientActivityEvent");
    private final static QName _ClientUpdateEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "ClientUpdateEvent");
    private final static QName _WebImpulse_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "WebImpulse");
    private final static QName _ClientReaction_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "ClientReaction");
    private final static QName _PromotionDecision_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "PromotionDecision");
    private final static QName _LoginEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "LoginEvent");
    private final static QName _Reaction_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "Reaction");
    private final static QName _MonitoringEventType_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "MonitoringEventType");
    private final static QName _ExpenseBookingEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "ExpenseBookingEvent");
    private final static QName _MonitoringEvent_QNAME = new QName("http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", "MonitoringEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.ia.xmlns._default.rsa_demobank_bom.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExpenseBookingEvent }
     * 
     */
    public ExpenseBookingEvent createExpenseBookingEvent() {
        return new ExpenseBookingEvent();
    }

    /**
     * Create an instance of {@link MonitoringEvent }
     * 
     */
    public MonitoringEvent createMonitoringEvent() {
        return new MonitoringEvent();
    }

    /**
     * Create an instance of {@link LoginEvent }
     * 
     */
    public LoginEvent createLoginEvent() {
        return new LoginEvent();
    }

    /**
     * Create an instance of {@link Reaction }
     * 
     */
    public Reaction createReaction() {
        return new Reaction();
    }

    /**
     * Create an instance of {@link CRMImpulse }
     * 
     */
    public CRMImpulse createCRMImpulse() {
        return new CRMImpulse();
    }

    /**
     * Create an instance of {@link ClientActivityEvent }
     * 
     */
    public ClientActivityEvent createClientActivityEvent() {
        return new ClientActivityEvent();
    }

    /**
     * Create an instance of {@link ClientUpdateEvent }
     * 
     */
    public ClientUpdateEvent createClientUpdateEvent() {
        return new ClientUpdateEvent();
    }

    /**
     * Create an instance of {@link WebImpulse }
     * 
     */
    public WebImpulse createWebImpulse() {
        return new WebImpulse();
    }

    /**
     * Create an instance of {@link ClientReaction }
     * 
     */
    public ClientReaction createClientReaction() {
        return new ClientReaction();
    }

    /**
     * Create an instance of {@link PromotionDecision }
     * 
     */
    public PromotionDecision createPromotionDecision() {
        return new PromotionDecision();
    }

    /**
     * Create an instance of {@link ClientSetupEvent }
     * 
     */
    public ClientSetupEvent createClientSetupEvent() {
        return new ClientSetupEvent();
    }

    /**
     * Create an instance of {@link CRMReaction }
     * 
     */
    public CRMReaction createCRMReaction() {
        return new CRMReaction();
    }

    /**
     * Create an instance of {@link Impulse }
     * 
     */
    public Impulse createImpulse() {
        return new Impulse();
    }

    /**
     * Create an instance of {@link LetterImpulse }
     * 
     */
    public LetterImpulse createLetterImpulse() {
        return new LetterImpulse();
    }

    /**
     * Create an instance of {@link LetterInputKeyValuePair }
     * 
     */
    public LetterInputKeyValuePair createLetterInputKeyValuePair() {
        return new LetterInputKeyValuePair();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientSetupEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "ClientSetupEvent")
    public JAXBElement<ClientSetupEvent> createClientSetupEvent(ClientSetupEvent value) {
        return new JAXBElement<ClientSetupEvent>(_ClientSetupEvent_QNAME, ClientSetupEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRMReaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "CRMReaction")
    public JAXBElement<CRMReaction> createCRMReaction(CRMReaction value) {
        return new JAXBElement<CRMReaction>(_CRMReaction_QNAME, CRMReaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Impulse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "Impulse")
    public JAXBElement<Impulse> createImpulse(Impulse value) {
        return new JAXBElement<Impulse>(_Impulse_QNAME, Impulse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LetterImpulse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "LetterImpulse")
    public JAXBElement<LetterImpulse> createLetterImpulse(LetterImpulse value) {
        return new JAXBElement<LetterImpulse>(_LetterImpulse_QNAME, LetterImpulse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRMImpulse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "CRMImpulse")
    public JAXBElement<CRMImpulse> createCRMImpulse(CRMImpulse value) {
        return new JAXBElement<CRMImpulse>(_CRMImpulse_QNAME, CRMImpulse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientActivityEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "ClientActivityEvent")
    public JAXBElement<ClientActivityEvent> createClientActivityEvent(ClientActivityEvent value) {
        return new JAXBElement<ClientActivityEvent>(_ClientActivityEvent_QNAME, ClientActivityEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientUpdateEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "ClientUpdateEvent")
    public JAXBElement<ClientUpdateEvent> createClientUpdateEvent(ClientUpdateEvent value) {
        return new JAXBElement<ClientUpdateEvent>(_ClientUpdateEvent_QNAME, ClientUpdateEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebImpulse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "WebImpulse")
    public JAXBElement<WebImpulse> createWebImpulse(WebImpulse value) {
        return new JAXBElement<WebImpulse>(_WebImpulse_QNAME, WebImpulse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientReaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "ClientReaction")
    public JAXBElement<ClientReaction> createClientReaction(ClientReaction value) {
        return new JAXBElement<ClientReaction>(_ClientReaction_QNAME, ClientReaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PromotionDecision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "PromotionDecision")
    public JAXBElement<PromotionDecision> createPromotionDecision(PromotionDecision value) {
        return new JAXBElement<PromotionDecision>(_PromotionDecision_QNAME, PromotionDecision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "LoginEvent")
    public JAXBElement<LoginEvent> createLoginEvent(LoginEvent value) {
        return new JAXBElement<LoginEvent>(_LoginEvent_QNAME, LoginEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "Reaction")
    public JAXBElement<Reaction> createReaction(Reaction value) {
        return new JAXBElement<Reaction>(_Reaction_QNAME, Reaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonitoringEventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "MonitoringEventType")
    public JAXBElement<MonitoringEventType> createMonitoringEventType(MonitoringEventType value) {
        return new JAXBElement<MonitoringEventType>(_MonitoringEventType_QNAME, MonitoringEventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpenseBookingEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "ExpenseBookingEvent")
    public JAXBElement<ExpenseBookingEvent> createExpenseBookingEvent(ExpenseBookingEvent value) {
        return new JAXBElement<ExpenseBookingEvent>(_ExpenseBookingEvent_QNAME, ExpenseBookingEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MonitoringEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model", name = "MonitoringEvent")
    public JAXBElement<MonitoringEvent> createMonitoringEvent(MonitoringEvent value) {
        return new JAXBElement<MonitoringEvent>(_MonitoringEvent_QNAME, MonitoringEvent.class, null, value);
    }

}
