//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2017.02.02 at 11:16:17 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(
		 xmlns = {
			        @javax.xml.bind.annotation.XmlNs(prefix = "m",
			                   namespaceURI="http://www.ibm.com/ia/xmlns/default/RSA_DemoBank_BOM/model")},
		
		
		 elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.ia.xmlns._default.rsa_demobank_bom.model;

